sqs2sf:
  handler: index.starter
  timeout: 200
  memory: 512
  source: 'node_modules/@cumulus/api/dist/'

executeMigrations:
  handler: index.executeMigrations
  timeout: 300
  useElasticSearch: '{{es.name}}'
  memory: 1024
  source: 'node_modules/@cumulus/api/dist/'
  envs:
    GranulesTable:
      function: Ref
      value: GranulesTableDynamoDB
    FilesTable:
      function: Ref
      value: FilesTableDynamoDB
    ExecutionsTable:
      function: Ref
      value: ExecutionsTableDynamoDB
    PdrsTable:
      function: Ref
      value: PdrsTableDynamoDB
    internal: '{{system_bucket}}'

sns2elasticsearch:
  handler: index.indexer
  timeout: 100
  useElasticSearch: '{{es.name}}'
  memory: 512
  source: 'node_modules/@cumulus/api/dist/'
  envs:
    GranulesTable:
      function: Ref
      value: GranulesTableDynamoDB
    ExecutionsTable:
      function: Ref
      value: ExecutionsTableDynamoDB
    PdrsTable:
      function: Ref
      value: PdrsTableDynamoDB

log2elasticsearch:
  handler: index.logHandler
  timeout: 100
  memory: 512
  useElasticSearch: '{{es.name}}'
  source: 'node_modules/@cumulus/api/dist/'

dbIndexer:
  handler: index.dbIndexer
  timeout: 300
  memory: 512
  source: 'node_modules/@cumulus/api/dist/'
  useElasticSearch: '{{es.name}}'
  envs:
    bucket: '{{system_bucket}}'
    FilesTable:
      function: Ref
      value: FilesTableDynamoDB

kinesisConsumer:
  handler: index.kinesisConsumer
  timeout: 100
  memory: 512
  source: 'node_modules/@cumulus/api/dist/'
  envs:
    RulesTable:
      function: Ref
      value: RulesTableDynamoDB
    CollectionsTable:
      function: Ref
      value: CollectionsTableDynamoDB
    ProvidersTable:
      function: Ref
      value: ProvidersTableDynamoDB
    bucket: '{{system_bucket}}'
    FallbackTopicArn:
      function: Fn::Sub
      value: '${kinesisFallbackSns}'

fallbackConsumer:
  handler: index.kinesisConsumer
  timeout: 100
  memory: 512
  source: 'node_modules/@cumulus/api/dist/'
  deadletterqueue: kinesisFailure
  envs:
    RulesTable:
      function: Ref
      value: RulesTableDynamoDB
    CollectionsTable:
      function: Ref
      value: CollectionsTableDynamoDB
    ProvidersTable:
      function: Ref
      value: ProvidersTableDynamoDB
    bucket: '{{system_bucket}}'

ScheduleSF:
  description: 'This lambda function is invoked by scheduled rules created via cumulus API'
  handler: index.scheduler
  timeout: 100
  memory: 512
  source: 'node_modules/@cumulus/api/dist/'
  envs:
    CollectionsTable:
      function: Ref
      value: CollectionsTableDynamoDB
    ProvidersTable:
      function: Ref
      value: ProvidersTableDynamoDB

jobs:
  handler: index.jobs
  timeout: 300
  memory: 512
  useElasticSearch: '{{es.name}}'
  source: 'node_modules/@cumulus/api/dist/'

# used as custom resource for cloudformation manipulation
CustomBootstrap:
  handler: index.bootstrap
  timeout: 300
  memory: 512
  source: 'node_modules/@cumulus/api/dist/'
  envs:
    internal: '{{system_bucket}}'
    stackName: '{{stackName}}'

InRegionS3Policy:
  handler: index.inRegionS3Policy
  memory: 512
  timeout: 300
  source: 'node_modules/@cumulus/api/dist/'

EmsReport:
  handler: index.emsReport
  timeout: 300
  memory: 512
  source: 'node_modules/@cumulus/api/dist/'
  useElasticSearch: '{{es.name}}'
  envs:
    bucket: '{{system_bucket}}'
    ems_provider: '{{ems.provider}}'

EmsDistributionReport:
  handler: index.emsDistributionReport
  timeout: 300
  memory: 512
  source: 'node_modules/@cumulus/api/dist/'
  envs:
    LOGS_BUCKET: '{{system_bucket}}'
    REPORTS_BUCKET: '{{system_bucket}}'
    STACK_NAME: '{{stackName}}'

CreateReconciliationReport:
  handler: index.createReconciliationReport
  source: 'node_modules/@cumulus/api/dist/'
  envs:
    systemBucket: '{{system_bucket}}'
    stackName: '{{stackName}}'
    filesTableName:
      function: Ref
      value: FilesTableDynamoDB

BulkDelete:
  handler: index.bulkDeleteLambda
  source: 'node_modules/@cumulus/api/dist/'
